### ISSUE TITLE
vba failes to execute, causing the run to fail before completion

### ISSUE THREAD

**Issue by LukeUsher** [gbdev/GBEmulatorShootout#13]
Spotted in the build log here: https://github.com/daid/GBEmulatorShootout/actions/runs/3210664275/jobs/5248281448

```
Downloading https://sourceforge.net/projects/vba/files/latest/download
Downloading https://gbdev.gg8.se/files/roms/bootroms/sgb_boot.bin
Downloading https://gbdev.gg8.se/files/roms/bootroms/cgb_boot.bin
Downloading https://gbdev.gg8.se/files/roms/bootroms/dmg_boot.bin
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\hostedtoolcache\windows\Python\3.10.7\x64\lib\subprocess.py", line 1438, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] The system cannot find the file specified
Error: Process completed with exit code 1.
```

**Comment by calc84maniac** [comment]
Something still seems broken in the automation for VBA. On the webpage generated based on this fix, it appears that VBA only ran one of the tests.

**Comment by daid** [comment]
Yeah, not sure what is up, sourceforge changed something in how they prioritize downloads and now it's grabbing the SDL version instead of the other version it was using. And that's causing some issues.
