### ISSUE TITLE
Idea: Add Mednafen

### ISSUE THREAD

**Issue by asiekierka** [gbdev/GBEmulatorShootout#15]
It has a GameBoy emulator core! Technically.

I'd do it myself, but the project seems highly Windows-specific, and I don't have a Windows machine :-(

**Comment by CasualPokePlayer** [comment]
To be clear its Game Boy core is itself a fork of VBA (not VBA-M to note). Not sure if it's going to be any better than the already present VBA results (and probably much worse than VBA-M).

The project isn't Windows specific really, you just have to compile it yourself if you are on non-Windows (it notes on its page it has been successfully compiled on FreeBSD/Linux/NetBSD/OpenBSD/Windows).

**Comment by asiekierka** [comment]
I meant the Shootout, not Mednafen:
```
import win32gui
```
If Mednafen is just a fork of VBA, then maybe there's no point...

**Comment by daid** [comment]
the shootout has a few win32 parts, but if you comment those out it should work on windows. However, if it's just re-skinned VBA, there is little use in adding it.
