### ISSUE TITLE
Gambatte possibly has another "correct" behavior for ​ppu_scanline_bgp.gb

### ISSUE THREAD

**Issue by CasualPokePlayer** [gbdev/GBEmulatorShootout#9]
I went ahead and tried to implement the behavior the test was looking for into Gambatte (it was extremely easy to implement). A problem  arised however, this behavior contradicts results from Gambatte's test suite.

I understand that this behavior isn't consistent between DMGs, although Gambatte doesn't seem to share the result bgb (considered "passing") has. It seems to boil down to 3 behaviors that can occur for a pixel.

1. Old BGP is read (bgb behavior)
2. Bitwise OR between old and new BGP is read (SameBoy behavior/what this test expects)
3. New BGP is read (Gambatte behavior/what Gambatte's test suite expects)

3 also appears to occur in CGB-DMG (tested on my own GB Player, and SameBoy also agrees this should be the case). However, bgb does not appear to do 3 in its CGB-DMG mode, instead still doing 1. This could maybe point to bgb instead actually having an off by one issue and actually doing 3 (but 1 is what appears to happen due to this off by one), but it could perhaps be revision specific.

Attaching one of Gambatte's testroms (there's several that fail, this is just one of them), the image that it expects, and a GBI screenshot (which matches). This testrom was also largely used for figuring out these differences. [dmgpalette_during_m3.zip](https://github.com/daid/GBEmulatorShootout/files/8407155/dmgpalette_during_m3.zip)

It might be best overall to just mark that test as "info" due to the multiple valid behaviors.

**Comment by daid** [comment]
Actually, the test passes on 1 or 2. It's a test that already has multiple "correct" outcomes:
https://github.com/daid/GBEmulatorShootout/blob/main/testroms/daid/ppu_scanline_bgp_0.png
https://github.com/daid/GBEmulatorShootout/blob/main/testroms/daid/ppu_scanline_bgp_1.png
https://github.com/daid/GBEmulatorShootout/blob/main/testroms/daid.py#L5

Adding the 3th one doesn't sound unreasonable. I'm quite sure this behavour is instance depended, so if you take 10 DMGs they don't all act the same.

My own DMG does 1 or 2 depending on the position in the scanline. So even if the gambatte testrom shows something, it might act different on a different scanline.
There is also difference between the stock screen and modded screens.


I didn't add this test to check for this mixing, I added the test to see if BGP writes mid scanline work, and if the timing is correct of those. So accepting different kinds of mixing is completely inline with the test itself.

**Comment by CasualPokePlayer** [comment]
Right, I know both 1 and 2 are passing (I noted as bgb and SameBoy are both passing). The 3rd I believe would also be a pass (given Gambatte's testroms saying so and that is the behavior of CGB, highly indicating that is a possible behavior).

On another note, I noticed this test gave quite different timing on my GB Player when I tried it on that. Perhaps this test should also run in CGB-DMG mode (and as a bonus, CGB shouldn't have this instance specific behavior, although I wouldn't know if it's revision specific behavior safe). Here's a screenshot of the test from my GB Player:
![image](https://user-images.githubusercontent.com/50538166/161519944-a5441373-1b9f-48bc-a02d-d0b496f7f348.png)

**Comment by daid** [comment]
Note that the CGB-DMG has slightly different scanline timing, this test is specifically for DMG, not CGB on DMG. Quite sure other emulators will show a slight shift if you run them in CGB-DMG mode as well.

**Comment by CasualPokePlayer** [comment]
Right, I'm proposing it should be run in CGB-DMG alongside DMG mode, to check if emulators are correctly emulating these timing differences.

**Comment by daid** [comment]
I'm currently focusing on other things. So I wouldn't mind a pull request adding this ;-)
